global:
  c4ghPath: c4gh
  jwtPath: jwt
  tlsPath: tls
  podSecurityPolicy:
    create: false
  archive:
    storageType: FileStorage
    existingClaim: archive-volume
  broker:
    host: "broker-sda-mq"
    exchange: "lega"
    port: 5671
    verifyPeer: false
    password: "admin"
    username: "admin"
  cega:
    host: "cega-users"
    user: "legatest"
  db:
    host: "postgres-sda-db"
  elixir:
    pubKey: "token.pub"
  inbox:
    storageType: FileStorage
    path: "/ega/inbox"
    user: "lega"
    existingClaim: inbox-volume
  log: debug
# Specific config per-service
ingest:
  repository: neicnordic/sda-pipeline
  imageTag: release-v0.1.1
  errorKey: "errmsg"
  routingKey: "archived"
  queue: "files"
verify:
  repository: neicnordic/sda-pipeline
  imageTag: release-v0.1.1
  errorKey: "errmsg"
  routingKey: "files.verified"
  queue: "archived"
finalize:
  repository: neicnordic/sda-pipeline
  imageTag: release-v0.1.1
  errorKey: "errmsg"
  routingKey: "files.completed"
  queue: "stableIDs"
doa:
  repository: neicnordic/sda-doa
  imageTag: release-v1.2.0
