global:
  c4ghPath: c4gh
  jwtPath: jwt
  tlsPath: tls
  podSecurityPolicy:
    create: false
  archive:
    storageType: S3Storage
    s3Url: "https://minio"
    s3Bucket: "archive"
    s3AccessKey: idDQBxLpXoM8l88l
    s3SecretKey: ABd6XCIvNWj7JULbrqBf8tB7q9BoHJSc
  auth:
    elixirID: DfCieZLuBU
    elixirSecret: DfCieZLuBU
    jwtKey: jwt.key
    jwtPub: token.pub
    useTLS: true
  broker:
    host: "broker-sda-mq"
    exchange: "lega"
    port: 5671
    verifyPeer: false
    password: "admin"
    username: "admin"
  cega:
    host: "cega-users"
    user: "legatest"
    password: 3iSGc5loLN7hu2EwT2Z2CzCT26iUrk3t
  c4gh:
    file: c4gh.key
    passphrase: oaagCP1YgAZeEyl2eJAkHv9lkcWXWFgm
  db:
    host: "postgres-sda-db"
  elixir:
    pubKey: token.pub
    oidcdHost: "http://oidc-server"
    jwkPath: ""
  inbox:
    storageType: S3Storage
    # existingClaim: test
    s3Url: "https://minio"
    s3Bucket: "archive"
    s3AccessKey: idDQBxLpXoM8l88l
    s3SecretKey: ABd6XCIvNWj7JULbrqBf8tB7q9BoHJSc
    s3CaFile: ca.crt
    s3ReadyPath: "/minio/health/ready"
  ingress:
    hostName:
      auth: sda-sda-svc-auth
  log: debug
# Specific config per-service
ingest:
  repository: neicnordic/sda-pipeline
  imageTag: release-v0.1.1
  errorKey: "errmsg"
  routingKey: "archived"
  queue: "files"
verify:
  repository: neicnordic/sda-pipeline
  imageTag: release-v0.1.1
  errorKey: "errmsg"
  routingKey: "files.verified"
  queue: "archived"
finalize:
  repository: neicnordic/sda-pipeline
  imageTag: release-v0.1.1
  errorKey: "errmsg"
  routingKey: "files.completed"
  queue: "stableIDs"
doa:
  repository: neicnordic/sda-doa
  imageTag: release-v1.2.0
s3Inbox:
  repository: neicnordic/sda-s3proxy
  imageTag: release-v0.1.2
