{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}-finalize
  labels:
    role: finalize
    app: {{ template "sda.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-finalize
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.global.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "sda.name" . }}-finalize
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sda.name" . }}-finalize
        role: finalize
        release: {{ .Release.Name }}
      annotations:
        {{- if not .Values.global.confFile }}
        checksum/secret: {{ include (print $.Template.BasePath "/shared-secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/finalize-secrets.yaml") . | sha256sum }}
        {{- end }}
{{- if .Values.global.podAnnotations }}
{{- toYaml .Values.global.podAnnotations | nindent 8 -}}
{{- end }}
{{- if .Values.finalize.annotations }}
{{- toYaml .Values.finalize.annotations | nindent 8 -}}
{{- end }}
    spec:
    {{- if .Values.global.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
    {{- end }}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
    {{- if .Values.global.pkiPermissions }}
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 65534:65534 /tls/* && chmod 0600 /tls/*"]
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
    {{- end }}
      containers:
      - name: finalize
        image: "{{ .Values.finalize.repository }}:{{ .Values.finalize.imageTag }}"
        imagePullPolicy: {{ .Values.finalize.imagePullPolicy | quote }}
        command: ["sda-finalize"]
        args: ["--log", {{ .Values.global.log | quote }}]
        securityContext:
          allowPrivilegeEscalation: false
        env:
        {{- if not .Values.finalize.confFile }}
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-finalize
                key: dbPassword
        - name: DB_USER
          value: {{ include "dbUserFinalize" . | quote }}
        - name: BROKER_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-finalize
                key: mqPassword
        - name: BROKER_USER
          value: {{ include "mqUserFinalize" . | quote }}

      {{- else }}
        - name: CONFIGFILE
          value: {{ include "confFile" . }}
      {{- end }}

        - name: DB_HOST
          value: {{ required "A valid DB host is required" .Values.global.db.host | quote }}
        - name: DB_PORT
          value: {{ .Values.global.db.port | quote }}
        - name: DB_DATABASE
          value: {{ required "A valid DB name is required" .Values.global.db.name | quote }}
        - name: DB_SSLMODE
          value: {{ .Values.global.db.sslMode | quote }}
        - name: DB_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
        - name: DB_CLIENTCERT
          value: {{ include "tlsPath" . }}/finalize.crt
        - name: DB_CLIENTKEY
          value: {{ include "tlsPath" . }}/finalize.key
        - name: BROKER_QUEUE
          value: {{ required "Broker queue for finalize missing" .Values.finalize.queue }}
        - name: BROKER_ROUTINGKEY
          value: {{ required "Broker routing key for finalize missing" .Values.finalize.routingKey }}
        - name: BROKER_ROUTINGERROR
          value: {{ required "Broker error routing key missing" .Values.finalize.errorKey }}
        - name: BROKER_HOST
          value: {{ required "A valid MQ host is required" .Values.global.broker.host | quote }}
        - name: BROKER_PORT
          value: {{ .Values.global.broker.port | quote }}
        - name: BROKER_VHOST
          value: {{ .Values.global.broker.vhost | quote }}
        - name: BROKER_SERVERNAME
          value: {{ .Values.global.broker.host | quote }}
        - name: BROKER_SSL
          value: "true"
        - name: BROKER_DURABLE
          value: {{ .Values.global.broker.durable | quote }}
        - name: BROKER_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
        - name: BROKER_VERIFYPEER
          value: {{ .Values.global.broker.verifyPeer | quote }}
      {{- if .Values.global.broker.verifyPeer }}
        - name: BROKER_CLIENTCERT
          value: {{ include "tlsPath" . }}/finalize.crt
        - name: BROKER_CLIENTKEY
          value: {{ include "tlsPath" . }}/finalize.key
      {{- end }}
        resources:
{{ toYaml .Values.finalize.resources | trim | indent 10 }}
        volumeMounts:
      {{- if not .Values.global.pkiService }}
        - name: tls
          mountPath: "{{ template "tlsPath" . }}"
      {{- end }}
      volumes:
    {{- if not .Values.global.pkiService }}
        - name: {{ ternary "tls" "tls-certs" (empty .Values.global.pkiPermissions) }}
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-finalize-certs
      {{- if .Values.global.pkiPermissions }}
        - name: tls
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
      {{- end }}
    {{- end }}
      restartPolicy: Always
{{- end }}
