{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}-verify
  labels:
    role: verify
    app: {{ template "sda.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-verify
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.global.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "sda.name" . }}-verify
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sda.name" . }}-verify
        role: verify
        release: {{ .Release.Name }}
      annotations:
        {{- if not .Values.global.confFile }}
        checksum/secret: {{ include (print $.Template.BasePath "/shared-secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/verify-secrets.yaml") . | sha256sum }}
        {{- end }}
{{- if .Values.global.podAnnotations }}
{{- toYaml .Values.global.podAnnotations | nindent 8 -}}
{{- end }}
{{- if .Values.verify.annotations }}
{{- toYaml .Values.verify.annotations | nindent 8 -}}
{{- end }}
    spec:
    {{- if .Values.global.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
    {{- end }}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
    {{- if .Values.global.pkiPermissions }}
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 65534:65534 /tls/* && chmod 0600 /tls/*"]
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
    {{- end }}
      containers:
      - name: verify
        image: "{{ .Values.verify.repository }}:{{ .Values.verify.imageTag }}"
        imagePullPolicy: {{ .Values.verify.imagePullPolicy | quote }}
        command: ["sda-verify"]
        args: ["--log", {{ .Values.global.log | quote }}]
        securityContext:
          allowPrivilegeEscalation: false
        env:
        {{- if not .Values.verify.confFile }}
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-verify
                key: dbPassword
        - name: DB_USER
          value: {{ include "dbUserVerify" . | quote }}
        - name: BROKER_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-verify
                key: mqPassword
        - name: BROKER_USER
          value: {{ include "mqUserVerify" . | quote }}
        {{- if eq "S3Storage" .Values.global.archive.storageType }}
        - name: ARCHIVE_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveAccessKey
        - name: ARCHIVE_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveSecretKey
        - name: C4GH_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-verify
              key: c4ghPassphrase
      {{- end }}

      {{- else }}
        - name: CONFIGFILE
          value: {{ include "confFile" . }}
      {{- end }}

        - name: C4GH_FILEPATH
          value: {{ template "c4ghPath" . }}/{{ default "c4gh.sec.pem" .Values.global.c4gh.file }}
        - name: DB_HOST
          value: {{ required "A valid DB host is required" .Values.global.db.host | quote }}
        - name: DB_PORT
          value: {{ .Values.global.db.port | quote }}
        - name: DB_DATABASE
          value: {{ required "A valid DB name is required" .Values.global.db.name | quote }}
        - name: DB_SSLMODE
          value: {{ .Values.global.db.sslMode | quote }}
        - name: DB_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
        - name: DB_CLIENTCERT
          value: {{ include "tlsPath" . }}/verify.crt
        - name: DB_CLIENTKEY
          value: {{ include "tlsPath" . }}/verify.key
        - name: ARCHIVE_TYPE
      {{- if eq "S3Storage" .Values.global.archive.storageType }}
          value: "s3"
        - name: ARCHIVE_URL
          value: {{ required "S3 archive URL missing" .Values.global.archive.s3Url }}
        - name: ARCHIVE_BUCKET
          value: {{ required "S3 archive bucket missing" .Values.global.archive.s3Bucket }}
        - name: ARCHIVE_REGION
          value: {{ default "us-east-1" .Values.global.archive.s3Region }}
        - name: ARCHIVE_CHUNKSIZE
          value: {{ .Values.global.archive.s3ChunkSize | mul 1048576 | quote }}
        - name: ARCHIVE_CACERT
          value: "{{ template "tlsPath" . }}/ca.crt"
      {{- else }}
          value: "posix"
        - name: ARCHIVE_LOCATION
          value: "{{ .Values.global.archive.volumePath }}/%s"
      {{- end }}
        - name: BROKER_QUEUE
          value: {{ required "Broker queue for verify missing" .Values.verify.queue }}
        - name: BROKER_ROUTINGKEY
          value: {{ required "Broker routing key for verify missing" .Values.verify.routingKey }}
        - name: BROKER_ROUTINGERROR
          value: {{ required "Broker error routing key missing" .Values.verify.errorKey }}
        - name: BROKER_HOST
          value: {{ required "A valid MQ host is required" .Values.global.broker.host | quote }}
        - name: BROKER_PORT
          value: {{ .Values.global.broker.port | quote }}
        - name: BROKER_VHOST
          value: {{ .Values.global.broker.vhost | quote }}
        - name: BROKER_SERVERNAME
          value: {{ .Values.global.broker.host | quote }}
        - name: BROKER_SSL
          value: "true"
        - name: BROKER_DURABLE
          value: {{ .Values.global.broker.durable | quote }}
        - name: BROKER_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
        - name: BROKER_VERIFYPEER
          value: {{ .Values.global.broker.verifyPeer | quote }}
      {{- if .Values.global.broker.verifyPeer }}
        - name: BROKER_CLIENTCERT
          value: {{ include "tlsPath" . }}/verify.crt
        - name: BROKER_CLIENTKEY
          value: {{ include "tlsPath" . }}/verify.key
      {{- end }}
        resources:
{{ toYaml .Values.verify.resources | trim | indent 10 }}
        volumeMounts:
      {{- if not .Values.global.pkiService }}
        - name: tls
          mountPath: "{{ template "tlsPath" . }}"
      {{- end }}
      {{- if eq "FileStorage" .Values.global.archive.storageType }}
        - name: archive
          mountPath: {{ .Values.global.archive.volumePath | quote }}
      {{- end }}
      volumes:
    {{- if not .Values.global.pkiService }}
        - name: {{ ternary "tls" "tls-certs" (empty .Values.global.pkiPermissions) }}
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-verify-certs
      {{- if .Values.global.pkiPermissions }}
        - name: tls
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
      {{- end }}
    {{- end }}
      {{- if eq "FileStorage" .Values.global.archive.storageType }}
        - name: archive
        {{- if .Values.global.archive.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.archive.existingClaim }}
        {{- else }}
          nfs:
            server: {{ required "An archive NFS server is required" .Values.global.archive.nfsServer | quote }}
            path: {{ if .Values.global.archive.nfsPath }}{{ .Values.global.archive.nfsPath | quote }}{{ else }}{{ "/" }}{{ end }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
{{- end }}
